INSERT INTO elecciones (
    nombre_oficial,
    pais,
    tipo_eleccion,
    codigo_metodo_electoral,
    fecha_inicio_jornada,
    fecha_cierre_jornada,
    modalidad_habilitada,
    tipo_circunscripcion,
    documento_no_votable,
    numero_curules,
    formula_cifra_repartidora,
    condicion_victoria,
    estado,
    modelos_candidatura,
    excciones_habilitadas,
    senado_config_json,
    camara_deptos_json,
    camara_especiales_json
) VALUES (
    'Eleccion Nacional 2026',
    'Colombia',
    'PRESIDENCIAL',
    'MAYORIA',
    '2026-05-10 08:00:00',
    '2026-05-10 16:00:00',
    'PRESENCIAL',
    'NACIONAL',
    'TI',
    1,
    NULL,
    'Mayoria simple',
    'ABIERTA',
    'INDIVIDUAL',
    'Discapacidad registrada, Fuerza publica activa',
    NULL,
    NULL,
    NULL
);