CREATE TABLE IF NOT EXISTS elecciones (
    id BIGSERIAL PRIMARY KEY,
    nombre_oficial VARCHAR(150) NOT NULL,
    pais VARCHAR(100) NOT NULL,
    tipo_eleccion VARCHAR(50) NOT NULL,
    codigo_metodo_electoral VARCHAR(10) NOT NULL,
    fecha_inicio_jornada TIMESTAMP NOT NULL,
    fecha_cierre_jornada TIMESTAMP NOT NULL,
    modalidad_habilitada VARCHAR(20) NOT NULL,
    tipo_circunscripcion VARCHAR(30) NOT NULL,
    jerarquia_geografica TEXT NOT NULL,
    circunscripciones_especiales TEXT,
    zona_horaria VARCHAR(80) NOT NULL,
    idioma VARCHAR(50) NOT NULL,
    documento_identidad_valido VARCHAR(80) NOT NULL,
    reglas_elegibilidad TEXT NOT NULL,
    umbral_primera_vuelta_porcentaje DOUBLE PRECISION,
    requiere_mas_uno_primera_vuelta BOOLEAN,
    porcentaje_umbral_listas DOUBLE PRECISION,
    numero_curules INTEGER,
    formula_cifra_repartidora VARCHAR(80),
    criterio_eliminacion VARCHAR(120),
    condicion_victoria VARCHAR(180),
    estado VARCHAR(30) NOT NULL
);